export const CHANGE_INPUT_VALUE = 'change_input_value'
export const CHANGE_CHOOSE = 'change_choose'
export const UPDATE_LIST = 'update_list'
export const CHANGE_TOTALPAGE = 'change_totalpage'
export const CHANGE_CURRENT = 'change_current'
export const SORT_BY_PRIORITY = 'sort_by_priority'
export const CHANGE_ITEM = 'change_item'
export const CHANGE_PRIORITY = 'change_priority'